{{- if .Values.secretData }}  # Conditional to skip if no secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eks-mega-chart.fullname" . }}-secret
  labels:
    {{- include "eks-mega-chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}